# Generated by Django 5.2 on 2025-04-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_is_consumer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_consumer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_seller',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SELLER', 'Seller'), ('CONSUMER', 'Consumer')], default='CONSUMER', max_length=10),
        ),
    ]
