# Generated by Django 5.2 on 2025-05-13 08:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_role_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='product_order',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='product_order',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='product_order',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product_order',
            name='total_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
