# Generated by Django 5.2 on 2025-05-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_product_order_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_order',
            name='name',
        ),
        migrations.AddField(
            model_name='product_order',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_order',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
