# Generated by Django 5.2 on 2025-05-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_product_order_name_product_order_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_order',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
