# Generated by Django 5.2 on 2025-05-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_product_order_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_order',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
