# Generated by Django 5.2 on 2025-05-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_contact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_order',
            name='status',
            field=models.CharField(default='completed', max_length=100),
        ),
    ]
